# Generated by Django 5.2.7 on 2025-12-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='biografia',
            field=models.TextField(blank=True, help_text='Pequeña descripción pública del usuario.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puntos',
            field=models.IntegerField(default=0, help_text='Puntos de contribución acumulados.'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('organizador', 'Organizador'), ('usuario', 'Usuario Registrado')], default='usuario', max_length=20),
        ),
    ]
