# Generated by Django 5.2.7 on 2025-11-05 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=200, verbose_name='Nombre del lugar')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('lat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Latitud')),
                ('lng', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitud')),
                ('categoria', models.CharField(choices=[('mirador', 'Mirador'), ('bar', 'Bar con encanto'), ('galeria', 'Galería'), ('tienda', 'Tienda local'), ('arte_urbano', 'Arte urbano'), ('plaza', 'Plaza'), ('otros', 'Otros')], db_index=True, default='otros', max_length=30, verbose_name='Categoría')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado de aprobación')),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo')),
                ('publicado', models.BooleanField(db_index=True, default=True, verbose_name='Publicado')),
                ('creado_por_id', models.IntegerField(db_index=True, verbose_name='ID del creador')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['lat', 'lng'], name='idx_lugar_coords'), models.Index(fields=['categoria', 'estado', 'publicado'], name='idx_lugar_filtros')],
            },
        ),
    ]
