# Generated by Django 5.2.7 on 2025-10-14 15:45

from django.db import migrations

def anadir_datos_iniciales(apps, schema_editor):
    """
    Añadimos aquí los lugares iniciales para la base de datos.
    """
    # Obtenemos el modelo 'Lugar' de la versión histórica de la app 'lugares'
    Lugar = apps.get_model('lugares', 'Lugar')

    # ¡Borra todos los lugares existentes para empezar de cero! (Opcional)
    Lugar.objects.all().delete()

    # Creamos una lista de lugares para añadir
    lugares_para_crear = [
        Lugar(
            nombre="Mirador de San Nicolás",
            descripcion="El mirador más famoso de Granada, con vistas espectaculares a la Alhambra y Sierra Nevada. Siempre lleno de vida, músicos y artesanos.",
            lat=37.1812,
            lng=-3.5932,
            categoria="mirador",
            estado="aprobado",
            publicado=True
        ),
        Lugar(
            nombre="Bar de Fede",
            descripcion="Un clásico del tapeo en Granada, famoso por su pescado frito y su ambiente auténtico. Un lugar pequeño pero con mucho encanto.",
            direccion="C. Marqués de Falces, 1, Centro, 18001 Granada",
            categoria="bar",
            estado="aprobado",
            publicado=True
        ),
        Lugar(
            nombre="El Gato Gordo (Grafiti)",
            descripcion="Un icónico grafiti del artista 'El Niño de las Pinturas' en el barrio del Realejo. Representa la esencia del arte urbano de Granada.",
            lat=37.1729,
            lng=-3.5957,
            categoria="arte_urbano",
            estado="aprobado",
            publicado=True
        ),
        Lugar(
            nombre="Carmen de los Mártires",
            descripcion="Unos jardines románticos junto a la Alhambra, ideales para un paseo tranquilo. Ofrece vistas diferentes de la ciudad y es un oasis de paz.",
            lat=37.1738,
            lng=-3.5905,
            categoria="plaza", # Usamos 'plaza' como categoría para parques/jardines
            estado="aprobado",
            publicado=True
        ),
        Lugar(
            nombre="Discos Bora-Bora",
            descripcion="Tienda de discos mítica en Granada. Un punto de encuentro para melómanos y un lugar perfecto para descubrir música nueva y vinilos.",
            direccion="Pl. de la Universidad, 1, Centro, 18001 Granada",
            categoria="tienda",
            estado="aprobado",
            publicado=True
        ),
        Lugar(
            nombre="Propuesta de concierto en el Zaidín",
            descripcion="Un evento propuesto por un usuario para un concierto en el barrio del Zaidín.",
            categoria="concierto",
            estado="pendiente", # Este estará pendiente de revisión
            publicado=True
        ),
    ]

    # Usamos bulk_create para insertar todos los lugares en una sola consulta a la BD.
    # Es mucho más eficiente que crear uno por uno.
    Lugar.objects.bulk_create(lugares_para_crear)


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(anadir_datos_iniciales),
    ]
