global:
  scrape_interval: 5s # Leer datos cada 5 segundos

scrape_configs:
  - job_name: 'culturemap-services'
    metrics_path: '/metrics'
    scheme: https
    static_configs:
      - targets:
        # PONE AQUÍ TUS DOMINIOS REALES (sin https:// al principio)
        - 'cm-usuarios.up.railway.app'
        - 'cm-lugares.up.railway.app'
        - 'cm-eventos.up.railway.app'
        - 'cm-interacciones.up.railway.app'
        - 'culturemap-app.up.railway.app'