# Generated by Django 5.2.8 on 2025-11-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('categoria', models.CharField(choices=[('concierto', 'Concierto'), ('exposicion', 'Exposición'), ('teatro', 'Teatro'), ('charla', 'Charla/Conferencia'), ('fiesta', 'Fiesta popular'), ('otros', 'Otros')], default='otros', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('publicado', 'Publicado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('creado_por_id', models.IntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
